package com.softyfy.common.exception;

public enum ErrorCode {

    SONG_NOT_FOUND,
    ARTIST_NOT_FOUND,
    ALBUM_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
    INVALID_REORDER_REQUEST,
    VALIDATION_FAILED,
    INVALID_SORT,
    UNSUPPORTED_MEDIA_TYPE,
    INVALID_FILE,
    FILE_TOO_LARGE,
    STORAGE_ERROR,
    CONFLICT,
    INTERNAL_ERROR
}
