import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

// Shared URL helpers for song audio + covers.
//
// AUDIO lives in a GitHub Release ("softyfy-audio-v1") as public assets. This
// replaced Google Drive streaming entirely: Drive's keyed API (alt=media) was
// 403'd by Google's anti-abuse flagging across every project/key we tried, and
// Drive's KEYLESS download endpoints fail cross-site by design (they reject
// browser requests carrying `Sec-Fetch-Site: cross-site`). GitHub release
// assets follow a 302 to a signed URL and answer `206 Partial Content` with
// byte ranges — exactly what <audio> + seeking need.
//
// Covers stay on Drive (`drive.google.com/thumbnail`), which allows cross-site
// image requests.

const ROOT = dirname(fileURLToPath(import.meta.url))
export const RELEASE_TAG = 'softyfy-audio-v1'
export const RELEASE_BASE = `https://github.com/pradipME/SoftyFy/releases/download/${RELEASE_TAG}`

// fileId → asset filename (see audio-release-map.json, generated by the
// migration that lifted the library out of Drive). Filenames are already
// sanitized to ASCII (spaces/parens → dots), so URLs need no extra encoding.
const AUDIO_MAP = JSON.parse(readFileSync(join(ROOT, 'audio-release-map.json'), 'utf8'))

export function assetName(fileId) {
  const name = AUDIO_MAP[fileId]
  if (!name) throw new Error(`no release asset mapped for fileId ${fileId}`)
  return name
}

export function audioUrl(fileId) {
  return `${RELEASE_BASE}/${assetName(fileId)}`
}

export function coverUrl(fileId) {
  return `https://drive.google.com/thumbnail?id=${encodeURIComponent(fileId)}&sz=w1000`
}