spring:
  datasource:
    url: jdbc:postgresql://${SOFTYFY_DB_HOST}:${SOFTYFY_DB_PORT:5432}/${SOFTYFY_DB_NAME}
    username: ${SOFTYFY_DB_USER}
    password: ${SOFTYFY_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
