spring:
  datasource:
    url: jdbc:postgresql://${SOFTYFY_DB_HOST:localhost}:${SOFTYFY_DB_PORT:5432}/${SOFTYFY_DB_NAME:softyfy}
    username: ${SOFTYFY_DB_USER:softyfy}
    password: ${SOFTYFY_DB_PASSWORD:softyfy}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.softyfy: INFO
